# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Secret Hitler main action.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Run melos script for pre-build checks
        run: melos run workflows:pre-build

  build-android:
    runs-on: macos-latest
    needs: pre-build

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - run: flutter build ios --release --no-codesign

  build-ios:
    runs-on: ubuntu-latest
    needs: pre-build

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - run: flutter build apk
      - run: flutter build appbundle


  build-web:
    runs-on: ubuntu-latest
    needs: pre-build

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - run: flutter build web